### ISSUE TITLE
关于 camera_v2驱动？

### ISSUE THREAD

**Issue by mxy218** [ztemt/NX531J_N_kernel#1]
努比亚7.1的内核用6.0的相机驱动？？？
不想开源还是随意敷衍？

**Comment by rover1312** [comment]
I think the camera is from 7.1 Development version or 3.05 en version.

**Comment by mxy218** [comment]
> I think the camera is from 7.1 Development version or 3.05 en version.

你自己同步marshmallow 和nougat源码的camera_v2对比代码。一模一样的。
