### ISSUE TITLE
求适配8.1/9.0！而且这个内核编译出来，nubia z11自己说内核损坏，编译两个系统了

### ISSUE THREAD

**Issue by zyppe** [ztemt/NX531J_N_kernel#2]
求适配8.1/9.0！而且这个内核编译出来，nubia z11自己说内核损坏，编译两个系统了！
官方别装死啊！

**Comment by Vaimibao** [comment]
> 求适配8.1/9.0！而且这个内核编译出来，nubia z11自己说内核损坏，编译两个系统了！
> 官方别装死啊！

挖坟，我编译是正常使用的，z11的7.1防误触内核就是修改这个源码直接编译而成
